export const FETCH_ALL_CRYPTO_COINS = 'FETCH_ALL_CRYPTO_COINS';
export const LOAD_STATUS_ALL_CRYPTO_COINS = 'LOAD_STATUS_ALL_CRYPTO_COINS';
export const SET_ALL_CRYPTO_COINS = 'SET_ALL_CRYPTO_COINS';
