export const FETCH_ALL_CRYPTO_DATA = 'FETCH_ALL_CRYPTO_DATA';
export const FETCH_NEW_CRYPTO_DATA = 'FETCH_NEW_CRYPTO_DATA';
export const SET_ALL_CRYPTO_DATA = 'SET_ALL_CRYPTO_DATA';
export const LOAD_STATUS_ALL_CRYPTO_DATA = 'LOAD_STATUS_ALL_CRYPTO_DATA';
export const CHANGE_PARAMS = 'CHANGE_PARAMS';
